project:
  type: website
  output-dir: _site

website:
  title: "ISSS626-GAA"
  navbar:
    left:
      - text: "Hands-on Exercise"
        menu:
        - text: "Exercise 1 - Geospatial Data Wrangling"
          href: "Hands-on_Ex/Hands-on_Ex01/Hands-on_Ex01a.html"
        - text: "Exercise 1 - Choropleth Mapping"
          href: "Hands-on_Ex/Hands-on_Ex01/Hands-on_Ex01b.html"
        - text: "Exercise 2 - 1st Order spatial point pattern analysis methods"
          href: "Hands-on_Ex/Hands-on_Ex02/Hands-on_Ex02a.html"
        - text: "Exercise 2 - 2nd Order spatial point pattern analysis methods"
          href: "Hands-on_Ex/Hands-on_Ex02/Hands-on_Ex02b.html"
    right:
      - href: index.qmd
        text: Home
      - about.qmd

format:
  html:
    theme: sandstone
    css: styles.css
    toc: true

editor: visual

